// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using POS365Computer.Api.Data;

#nullable disable

namespace POS365Computer.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260609165043_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("POS365Computer.Api.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "laptop",
                            Name = "Laptop"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "cpu",
                            Name = "Linh kiện máy tính"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "mouse",
                            Name = "Phụ kiện"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "printer",
                            Name = "Thiết bị văn phòng"
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2024, 5, 23, 8, 0, 0, 0, DateTimeKind.Utc),
                            Email = "a@example.com",
                            Name = "Nguyễn Văn A",
                            Phone = "0901000001"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2024, 5, 23, 9, 0, 0, 0, DateTimeKind.Utc),
                            Email = "b@example.com",
                            Name = "Trần Thị B",
                            Phone = "0901000002"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2024, 5, 23, 10, 0, 0, 0, DateTimeKind.Utc),
                            Email = "c@example.com",
                            Name = "Lê Văn C",
                            Phone = "0901000003"
                        },
                        new
                        {
                            Id = 4,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2024, 5, 23, 11, 0, 0, 0, DateTimeKind.Utc),
                            Email = "d@example.com",
                            Name = "Phạm Thị D",
                            Phone = "0901000004"
                        },
                        new
                        {
                            Id = 5,
                            Address = "Hà Nội",
                            CreatedAt = new DateTime(2024, 5, 23, 12, 0, 0, 0, DateTimeKind.Utc),
                            Email = "e@example.com",
                            Name = "Hoàng Văn E",
                            Phone = "0901000005"
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.InventoryTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("InventoryTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Seed laptop stock",
                            ProductId = 1,
                            Quantity = 120,
                            Type = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Seed component stock",
                            ProductId = 6,
                            Quantity = 320,
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Seed accessory stock",
                            ProductId = 3,
                            Quantity = 260,
                            Type = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            Note = "Seed office device stock",
                            ProductId = 5,
                            Quantity = 150,
                            Type = 1
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("OrderedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "DH10045",
                            CustomerId = 1,
                            OrderedAt = new DateTime(2024, 5, 23, 14, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalAmount = 15490000m
                        },
                        new
                        {
                            Id = 2,
                            Code = "DH10044",
                            CustomerId = 2,
                            OrderedAt = new DateTime(2024, 5, 23, 14, 15, 0, 0, DateTimeKind.Utc),
                            Status = 2,
                            TotalAmount = 2390000m
                        },
                        new
                        {
                            Id = 3,
                            Code = "DH10043",
                            CustomerId = 3,
                            OrderedAt = new DateTime(2024, 5, 23, 13, 50, 0, 0, DateTimeKind.Utc),
                            Status = 3,
                            TotalAmount = 950000m
                        },
                        new
                        {
                            Id = 4,
                            Code = "DH10042",
                            CustomerId = 4,
                            OrderedAt = new DateTime(2024, 5, 23, 13, 20, 0, 0, DateTimeKind.Utc),
                            Status = 4,
                            TotalAmount = 350000m
                        },
                        new
                        {
                            Id = 5,
                            Code = "DH10041",
                            CustomerId = 5,
                            OrderedAt = new DateTime(2024, 5, 23, 12, 45, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            TotalAmount = 25880000m
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LineTotal = 15490000m,
                            OrderId = 1,
                            ProductId = 2,
                            Quantity = 1,
                            UnitPrice = 15490000m
                        },
                        new
                        {
                            Id = 2,
                            LineTotal = 2390000m,
                            OrderId = 2,
                            ProductId = 5,
                            Quantity = 1,
                            UnitPrice = 2390000m
                        },
                        new
                        {
                            Id = 3,
                            LineTotal = 950000m,
                            OrderId = 3,
                            ProductId = 4,
                            Quantity = 1,
                            UnitPrice = 950000m
                        },
                        new
                        {
                            Id = 4,
                            LineTotal = 350000m,
                            OrderId = 4,
                            ProductId = 3,
                            Quantity = 1,
                            UnitPrice = 350000m
                        },
                        new
                        {
                            Id = 5,
                            LineTotal = 25880000m,
                            OrderId = 5,
                            ProductId = 6,
                            Quantity = 1,
                            UnitPrice = 25880000m
                        },
                        new
                        {
                            Id = 6,
                            LineTotal = 225000000m,
                            OrderId = 1,
                            ProductId = 1,
                            Quantity = 15,
                            UnitPrice = 15000000m
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("CostPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("nvarchar(600)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CostPrice = 18000000m,
                            Description = "Laptop văn phòng hiệu năng ổn định",
                            ImageUrl = "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=760&q=80",
                            Name = "Laptop Dell Inspiron 15 3520",
                            Price = 22500000m,
                            Sku = "LAP-DELL-3520",
                            Status = 1,
                            StockQuantity = 36
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CostPrice = 12200000m,
                            Description = "Mỏng nhẹ cho học tập và làm việc",
                            ImageUrl = "https://images.unsplash.com/photo-1603302576837-37561b2e2302?auto=format&fit=crop&w=760&q=80",
                            Name = "Laptop ASUS VivoBook 15 X1504VA",
                            Price = 15490000m,
                            Sku = "LAP-ASUS-X1504VA",
                            Status = 1,
                            StockQuantity = 42
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            CostPrice = 220000m,
                            Description = "Chuột yên tĩnh cho văn phòng",
                            ImageUrl = "https://images.unsplash.com/photo-1527814050087-3793815479db?auto=format&fit=crop&w=760&q=80",
                            Name = "Chuột không dây Logitech M331",
                            Price = 350000m,
                            Sku = "ACC-LOGI-M331",
                            Status = 1,
                            StockQuantity = 95
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 3,
                            CostPrice = 690000m,
                            Description = "Bàn phím cơ layout gọn",
                            ImageUrl = "https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=760&q=80",
                            Name = "Bàn phím cơ DareU EK87",
                            Price = 950000m,
                            Sku = "ACC-DAREU-EK87",
                            Status = 1,
                            StockQuantity = 64
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 4,
                            CostPrice = 1800000m,
                            Description = "Màn hình IPS 24 inch cho văn phòng",
                            ImageUrl = "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=760&q=80",
                            Name = "Màn hình LG 24MP400-B 24 inch",
                            Price = 2390000m,
                            Sku = "MON-LG-24MP400",
                            Status = 1,
                            StockQuantity = 53
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CostPrice = 21700000m,
                            Description = "Bộ máy chơi game, thiết kế đồ họa",
                            ImageUrl = "https://images.unsplash.com/photo-1587202372775-e229f172b9d7?auto=format&fit=crop&w=760&q=80",
                            Name = "PC Gaming M2T RTX 4060",
                            Price = 25880000m,
                            Sku = "PC-M2T-4060",
                            Status = 1,
                            StockQuantity = 30
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 5, 23, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Admin",
                            PasswordHash = "91C1042178F5ED4A7D83E023772157BEC94C04C8C9526B02494FAC2AFAB3D2CA",
                            Role = 1,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.InventoryTransaction", b =>
                {
                    b.HasOne("POS365Computer.Api.Entities.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Order", b =>
                {
                    b.HasOne("POS365Computer.Api.Entities.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.OrderItem", b =>
                {
                    b.HasOne("POS365Computer.Api.Entities.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("POS365Computer.Api.Entities.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Product", b =>
                {
                    b.HasOne("POS365Computer.Api.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Order", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("POS365Computer.Api.Entities.Product", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
